### PR TITLE
fixes/bugs_fixes: complete

### PR DESCRIPTION
**Pull request by SabiMantock**
main features:
- modified styling

### CODE REVIEW

**Review by Ghiftee — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️♻️
Hello team👋🏽 

Good job working on the project so far! 
To highlight 👍🏽 
✔️ You gave each other reviews
✔️ Your README is professional
✔️ Your app works as expected
✔️ All tests pass
However, there are some issues that you need to work on to go to the next project but you are almost there!



## Required Changes ♻️
- [x] According to the requirements, your design should look similar to the mockup design. Kindly edit the following designs:

### Design footer

Screenshot 2023-01-21 at 16 11 23 (2)

### Your footer

Screenshot 2023-01-21 at 15 59 30 (2)

### Your comments popup

Screenshot 2023-01-21 at 15 57 45 (2)
Screenshot 2023-01-21 at 15 57 52 (2)

### Design comments popup

Screenshot 2023-01-21 at 16 16 08 (2)

- [x] You are currently missing the requirement below, kindly implement it.
Screenshot 2023-01-21 at 16 40 42 (2)

- [x] Kindly create more unit tests, especially for counter functions. They should cover all edge cases e.g a scenario in which there are 0 items on the page (counter function should return 0)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by SabiMantock** [comment]
@Ghiftee, please I noticed that you used my live demo link from my readme. that link doesn't have the current updated changes. it will only be updated after it has been merged into the dev branch.

**Comment by SabiMantock** [comment]
@Ghiftee, it also said we could personalize our styling.
image

**Comment by Ghiftee** [comment]
@SabiMantock yes it says you can personalize the colors, typography and spacing but the same layout should be followed

**Comment by SabiMantock** [comment]
> @SabiMantock yes it says you can personalize the colors, typography, and spacing but the same layout should be followed

yes. but what you reviewed was the live demo from my dev branch.

**Comment by Ghiftee** [comment]
> @Ghiftee, please I noticed that you used my live demo link from my readme. that link doesn't have the current updated changes. it will only be updated after it has been merged into the dev branch.

My bad, that was an oversight, I should have invalidated the project since the review was not from the dev branch

**Comment by SabiMantock** [comment]
> > @Ghiftee, please I noticed that you used my live demo link from my readme. that link doesn't have the current updated changes. it will only be updated after it has been merged into the dev branch.
> 
> My bad, that was an oversight, I should have invalidated the project since the review was not from the dev branch

No worries

**Comment by Ghiftee** [comment]
Kindly submit a review from the dev branch and add a note in the PR about this branch for the next reviewer

**Review by BregornOriginal — APPROVED** [review]
## Hi @SabiMantock  

## In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it 🟢 🟢 🟢 

tenor-1


## Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
